// <auto-generated />
namespace Longhorn_Bank.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lastattempt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lastattempt));
        
        string IMigrationMetadata.Id
        {
            get { return "201705051309331_lastattempt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
