using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Longhorn_Bank.Models;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Longhorn_Bank.Migrations
{
    public class SeedIdentity
    {
        public static void SeedUsers(AppDbContext db)
        {
            //create a user manager to add users to databases
            UserManager<AppUser> userManager = new UserManager<AppUser>(new UserStore<AppUser>(db));
            userManager.PasswordValidator = new PasswordValidator
            {
                RequiredLength = 6,
                RequireNonLetterOrDigit = false,
                RequireDigit = false,
                RequireLowercase = false,
                RequireUppercase = false
            };

            //create a role manager
            AppRoleManager roleManager = new AppRoleManager(new RoleStore<AppRole>(db));

            //create an admin role
            String roleName = "User";
            //check to see if the role exists
            if (roleManager.RoleExists(roleName) == false) //role doesn't exist
            {
                roleManager.Create(new AppRole(roleName));
            }

            String Manager = "Manager";
            if (roleManager.RoleExists(Manager) == false) //role doesn't exist
            {
                roleManager.Create(new AppRole(Manager));
            }
            String Employee = "Employee";
            if (roleManager.RoleExists(Employee) == false) //role doesn't exist
            {
                roleManager.Create(new AppRole(Employee));
            }

            //create users
            String stru1Email = "cbaker@example.com";
            AppUser u1 = new AppUser();
            u1.Email = stru1Email;
            u1.UserName = stru1Email;
            u1.FirstName = "Christopher";
            u1.LastName = "Baker";
            u1.MiddleInitial = "L";
            u1.Address = "1245 Lake Austin Blvd.";
            u1.City = "Austin";
            u1.State = StateAbrv.TX;
            u1.ZipCode = "78733";
            u1.PhoneNumber = "5125571146";
            u1.DOB = DateTime.Parse("2/7/1991");
            AppUser userToAdd1 = userManager.FindByName(stru1Email); if (userToAdd1 == null)
            {
                userManager.Create(u1, "gazing"); userToAdd1 = userManager.FindByName(stru1Email); db.SaveChanges(); if (userManager.IsInRole(userToAdd1.Id, roleName) == false) { userManager.AddToRole(userToAdd1.Id, roleName); }

            }

            String stru2Email = "mb@aool.com"; AppUser u2 = new AppUser(); u2.Email = stru2Email; u2.UserName = stru2Email; u2.FirstName = "Michelle"; u2.LastName = "Banks"; u2.MiddleInitial = ""; u2.Address = "1300 Tall Pine Lane"; u2.City = "San Antonio"; u2.State = StateAbrv.TX; u2.ZipCode = "78261"; u2.PhoneNumber = "2102678873"; u2.DOB = DateTime.Parse("6/23/1990");
            String stru3Email = "fd@aool.com"; AppUser u3 = new AppUser(); u3.Email = stru3Email; u3.UserName = stru3Email; u3.FirstName = "Franco"; u3.LastName = "Broccolo"; u3.MiddleInitial = "V"; u3.Address = "62 Browning Rd"; u3.City = "Houston"; u3.State = StateAbrv.TX; u3.ZipCode = "77019"; u3.PhoneNumber = "8175659699"; u3.DOB = DateTime.Parse("5/6/1986");
            String stru4Email = "wendy@ggmail.com"; AppUser u4 = new AppUser(); u4.Email = stru4Email; u4.UserName = stru4Email; u4.FirstName = "Wendy"; u4.LastName = "Chang"; u4.MiddleInitial = "L"; u4.Address = "202 Bellmont Hall"; u4.City = "Austin"; u4.State = StateAbrv.TX; u4.ZipCode = "78713"; u4.PhoneNumber = "5125943222"; u4.DOB = DateTime.Parse("12/21/1964");
            String stru5Email = "limchou@yaho.com"; AppUser u5 = new AppUser(); u5.Email = stru5Email; u5.UserName = stru5Email; u5.FirstName = "Lim"; u5.LastName = "Chou"; u5.MiddleInitial = ""; u5.Address = "1600 Teresa Lane"; u5.City = "San Antonio"; u5.State = StateAbrv.TX; u5.ZipCode = "78266"; u5.PhoneNumber = "2107724599"; u5.DOB = DateTime.Parse("6/14/1950");
            String stru6Email = "Dixon@aool.com"; AppUser u6 = new AppUser(); u6.Email = stru6Email; u6.UserName = stru6Email; u6.FirstName = "Shan"; u6.LastName = "Dixon"; u6.MiddleInitial = "D"; u6.Address = "234 Holston Circle"; u6.City = "Dallas"; u6.State = StateAbrv.TX; u6.ZipCode = "75208"; u6.PhoneNumber = "2142643255"; u6.DOB = DateTime.Parse("5/9/1930");
            String stru7Email = "louann@ggmail.com"; AppUser u7 = new AppUser(); u7.Email = stru7Email; u7.UserName = stru7Email; u7.FirstName = "Lou Ann"; u7.LastName = "Feeley"; u7.MiddleInitial = "K"; u7.Address = "600 S 8th Street W"; u7.City = "Houston"; u7.State = StateAbrv.TX; u7.ZipCode = "77010"; u7.PhoneNumber = "8172556749"; u7.DOB = DateTime.Parse("2/24/1930");
            String stru8Email = "tfreeley@minntonka.ci.state.mn.us"; AppUser u8 = new AppUser(); u8.Email = stru8Email; u8.UserName = stru8Email; u8.FirstName = "Tesa"; u8.LastName = "Freeley"; u8.MiddleInitial = "P"; u8.Address = "4448 Fairview Ave."; u8.City = "Houston"; u8.State = StateAbrv.TX; u8.ZipCode = "77009"; u8.PhoneNumber = "8173255687"; u8.DOB = DateTime.Parse("9/1/1935");
            String stru9Email = "mgar@aool.com"; AppUser u9 = new AppUser(); u9.Email = stru9Email; u9.UserName = stru9Email; u9.FirstName = "Margaret"; u9.LastName = "Garcia"; u9.MiddleInitial = "L"; u9.Address = "594 Longview"; u9.City = "Houston"; u9.State = StateAbrv.TX; u9.ZipCode = "77003"; u9.PhoneNumber = "8176593544"; u9.DOB = DateTime.Parse("7/3/1990");
            String stru10Email = "chaley@thug.com"; AppUser u10 = new AppUser(); u10.Email = stru10Email; u10.UserName = stru10Email; u10.FirstName = "Charles"; u10.LastName = "Haley"; u10.MiddleInitial = "E"; u10.Address = "One Cowboy Pkwy"; u10.City = "Dallas"; u10.State = StateAbrv.TX; u10.ZipCode = "75261"; u10.PhoneNumber = "2148475583"; u10.DOB = DateTime.Parse("9/17/1985");
            String stru11Email = "jeff@ggmail.com"; AppUser u11 = new AppUser(); u11.Email = stru11Email; u11.UserName = stru11Email; u11.FirstName = "Jeffrey"; u11.LastName = "Hampton"; u11.MiddleInitial = "T"; u11.Address = "337 38th St."; u11.City = "Austin"; u11.State = StateAbrv.TX; u11.ZipCode = "78705"; u11.PhoneNumber = "5126978613"; u11.DOB = DateTime.Parse("1/23/1995");
            String stru12Email = "wjhearniii@umch.edu"; AppUser u12 = new AppUser(); u12.Email = stru12Email; u12.UserName = stru12Email; u12.FirstName = "John"; u12.LastName = "Hearn"; u12.MiddleInitial = "B"; u12.Address = "4225 North First"; u12.City = "Dallas"; u12.State = StateAbrv.TX; u12.ZipCode = "75237"; u12.PhoneNumber = "2148965621"; u12.DOB = DateTime.Parse("1/8/1994");
            String stru13Email = "hicks43@ggmail.com"; AppUser u13 = new AppUser(); u13.Email = stru13Email; u13.UserName = stru13Email; u13.FirstName = "Anthony"; u13.LastName = "Hicks"; u13.MiddleInitial = "J"; u13.Address = "32 NE Garden Ln., Ste 910"; u13.City = "San Antonio"; u13.State = StateAbrv.TX; u13.ZipCode = "78239"; u13.PhoneNumber = "2105788965"; u13.DOB = DateTime.Parse("10/6/1990");
            String stru14Email = "bradsingram@mall.utexas.edu"; AppUser u14 = new AppUser(); u14.Email = stru14Email; u14.UserName = stru14Email; u14.FirstName = "Brad"; u14.LastName = "Ingram"; u14.MiddleInitial = "S"; u14.Address = "6548 La Posada Ct."; u14.City = "Austin"; u14.State = StateAbrv.TX; u14.ZipCode = "78736"; u14.PhoneNumber = "5124678821"; u14.DOB = DateTime.Parse("4/12/1984");
            String stru15Email = "mother.Ingram@aool.com"; AppUser u15 = new AppUser(); u15.Email = stru15Email; u15.UserName = stru15Email; u15.FirstName = "Todd"; u15.LastName = "Jacobs"; u15.MiddleInitial = "L"; u15.Address = "4564 Elm St."; u15.City = "Austin"; u15.State = StateAbrv.TX; u15.ZipCode = "78731"; u15.PhoneNumber = "5124653365"; u15.DOB = DateTime.Parse("4/4/1983");
            String stru16Email = "victoria@aool.com"; AppUser u16 = new AppUser(); u16.Email = stru16Email; u16.UserName = stru16Email; u16.FirstName = "Victoria"; u16.LastName = "Lawrence"; u16.MiddleInitial = "M"; u16.Address = "6639 Butterfly Ln."; u16.City = "Austin"; u16.State = StateAbrv.TX; u16.ZipCode = "78761"; u16.PhoneNumber = "5129457399"; u16.DOB = DateTime.Parse("2/3/1961");
            String stru17Email = "lineback@flush.net"; AppUser u17 = new AppUser(); u17.Email = stru17Email; u17.UserName = stru17Email; u17.FirstName = "Erik"; u17.LastName = "Lineback"; u17.MiddleInitial = "W"; u17.Address = "1300 Netherland St"; u17.City = "San Antonio"; u17.State = StateAbrv.TX; u17.ZipCode = "78293"; u17.PhoneNumber = "2102449976"; u17.DOB = DateTime.Parse("9/3/1946");
            String stru18Email = "elowe@netscrape.net"; AppUser u18 = new AppUser(); u18.Email = stru18Email; u18.UserName = stru18Email; u18.FirstName = "Ernest"; u18.LastName = "Lowe"; u18.MiddleInitial = "S"; u18.Address = "3201 Pine Drive"; u18.City = "San Antonio"; u18.State = StateAbrv.TX; u18.ZipCode = "78279"; u18.PhoneNumber = "2105344627"; u18.DOB = DateTime.Parse("2/7/1992");
            String stru19Email = "luce_chuck@ggmail.com"; AppUser u19 = new AppUser(); u19.Email = stru19Email; u19.UserName = stru19Email; u19.FirstName = "Chuck"; u19.LastName = "Luce"; u19.MiddleInitial = "B"; u19.Address = "2345 Rolling Clouds"; u19.City = "San Antonio"; u19.State = StateAbrv.TX; u19.ZipCode = "78268"; u19.PhoneNumber = "2106983548"; u19.DOB = DateTime.Parse("10/25/1942");
            String stru20Email = "mackcloud@pimpdaddy.com"; AppUser u20 = new AppUser(); u20.Email = stru20Email; u20.UserName = stru20Email; u20.FirstName = "Jennifer"; u20.LastName = "MacLeod"; u20.MiddleInitial = "D"; u20.Address = "2504 Far West Blvd."; u20.City = "Austin"; u20.State = StateAbrv.TX; u20.ZipCode = "78731"; u20.PhoneNumber = "5124748138"; u20.DOB = DateTime.Parse("8/6/1965");
            String stru21Email = "liz@ggmail.com"; AppUser u21 = new AppUser(); u21.Email = stru21Email; u21.UserName = stru21Email; u21.FirstName = "Elizabeth"; u21.LastName = "Markham"; u21.MiddleInitial = "P"; u21.Address = "7861 Chevy Chase"; u21.City = "Austin"; u21.State = StateAbrv.TX; u21.ZipCode = "78732"; u21.PhoneNumber = "5124579845"; u21.DOB = DateTime.Parse("4/13/1959");
            String stru22Email = "mclarence@aool.com"; AppUser u22 = new AppUser(); u22.Email = stru22Email; u22.UserName = stru22Email; u22.FirstName = "Clarence"; u22.LastName = "Martin"; u22.MiddleInitial = "A"; u22.Address = "87 Alcedo St."; u22.City = "Houston"; u22.State = StateAbrv.TX; u22.ZipCode = "77045"; u22.PhoneNumber = "8174955201"; u22.DOB = DateTime.Parse("1/6/1990");
            String stru23Email = "smartinmartin.Martin@aool.com"; AppUser u23 = new AppUser(); u23.Email = stru23Email; u23.UserName = stru23Email; u23.FirstName = "Gregory"; u23.LastName = "Martinez"; u23.MiddleInitial = "R"; u23.Address = "8295 Sunset Blvd."; u23.City = "Houston"; u23.State = StateAbrv.TX; u23.ZipCode = "77030"; u23.PhoneNumber = "8178746718"; u23.DOB = DateTime.Parse("10/9/1987");
            String stru24Email = "cmiller@mapster.com"; AppUser u24 = new AppUser(); u24.Email = stru24Email; u24.UserName = stru24Email; u24.FirstName = "Charles"; u24.LastName = "Miller"; u24.MiddleInitial = "R"; u24.Address = "8962 Main St."; u24.City = "Houston"; u24.State = StateAbrv.TX; u24.ZipCode = "77031"; u24.PhoneNumber = "8177458615"; u24.DOB = DateTime.Parse("7/21/1984");
            String stru25Email = "nelson.Kelly@aool.com"; AppUser u25 = new AppUser(); u25.Email = stru25Email; u25.UserName = stru25Email; u25.FirstName = "Kelly"; u25.LastName = "Nelson"; u25.MiddleInitial = "T"; u25.Address = "2601 Red River"; u25.City = "Austin"; u25.State = StateAbrv.TX; u25.ZipCode = "78703"; u25.PhoneNumber = "5122926966"; u25.DOB = DateTime.Parse("7/4/1956");
            String stru26Email = "jojoe@ggmail.com"; AppUser u26 = new AppUser(); u26.Email = stru26Email; u26.UserName = stru26Email; u26.FirstName = "Joe"; u26.LastName = "Nguyen"; u26.MiddleInitial = "C"; u26.Address = "1249 4th SW St."; u26.City = "Dallas"; u26.State = StateAbrv.TX; u26.ZipCode = "75238"; u26.PhoneNumber = "2143125897"; u26.DOB = DateTime.Parse("1/29/1963");
            String stru27Email = "orielly@foxnets.com"; AppUser u27 = new AppUser(); u27.Email = stru27Email; u27.UserName = stru27Email; u27.FirstName = "Bill"; u27.LastName = "O'Reilly"; u27.MiddleInitial = "T"; u27.Address = "8800 Gringo Drive"; u27.City = "San Antonio"; u27.State = StateAbrv.TX; u27.ZipCode = "78260"; u27.PhoneNumber = "2103450925"; u27.DOB = DateTime.Parse("1/7/1983");
            String stru28Email = "or@aool.com"; AppUser u28 = new AppUser(); u28.Email = stru28Email; u28.UserName = stru28Email; u28.FirstName = "Anka"; u28.LastName = "Radkovich"; u28.MiddleInitial = "L"; u28.Address = "1300 Elliott Pl"; u28.City = "Dallas"; u28.State = StateAbrv.TX; u28.ZipCode = "75260"; u28.PhoneNumber = "2142345566"; u28.DOB = DateTime.Parse("3/31/1980");
            String stru29Email = "megrhodes@freezing.co.uk"; AppUser u29 = new AppUser(); u29.Email = stru29Email; u29.UserName = stru29Email; u29.FirstName = "Megan"; u29.LastName = "Rhodes"; u29.MiddleInitial = "C"; u29.Address = "4587 Enfield Rd."; u29.City = "Austin"; u29.State = StateAbrv.TX; u29.ZipCode = "78707"; u29.PhoneNumber = "5123744746"; u29.DOB = DateTime.Parse("8/12/1944");
            String stru30Email = "erynrice@aool.com"; AppUser u30 = new AppUser(); u30.Email = stru30Email; u30.UserName = stru30Email; u30.FirstName = "Eryn"; u30.LastName = "Rice"; u30.MiddleInitial = "M"; u30.Address = "3405 Rio Grande"; u30.City = "Austin"; u30.State = StateAbrv.TX; u30.ZipCode = "78705"; u30.PhoneNumber = "5123876657"; u30.DOB = DateTime.Parse("8/2/1934");
            String stru31Email = "jorge@hootmail.com"; AppUser u31 = new AppUser(); u31.Email = stru31Email; u31.UserName = stru31Email; u31.FirstName = "Jorge"; u31.LastName = "Rodriguez"; u31.MiddleInitial = ""; u31.Address = "6788 Cotter Street"; u31.City = "Houston"; u31.State = StateAbrv.TX; u31.ZipCode = "77057"; u31.PhoneNumber = "8178904374"; u31.DOB = DateTime.Parse("8/11/1989");
            String stru32Email = "ra@aoo.com"; AppUser u32 = new AppUser(); u32.Email = stru32Email; u32.UserName = stru32Email; u32.FirstName = "Allen"; u32.LastName = "Rogers"; u32.MiddleInitial = "B"; u32.Address = "4965 Oak Hill"; u32.City = "Austin"; u32.State = StateAbrv.TX; u32.ZipCode = "78732"; u32.PhoneNumber = "5128752943"; u32.DOB = DateTime.Parse("8/27/1967");
            String stru33Email = "st-jean@home.com"; AppUser u33 = new AppUser(); u33.Email = stru33Email; u33.UserName = stru33Email; u33.FirstName = "Olivier"; u33.LastName = "Saint-Jean"; u33.MiddleInitial = "M"; u33.Address = "255 Toncray Dr."; u33.City = "San Antonio"; u33.State = StateAbrv.TX; u33.ZipCode = "78292"; u33.PhoneNumber = "2104145678"; u33.DOB = DateTime.Parse("7/8/1950");
            String stru34Email = "ss34@ggmail.com"; AppUser u34 = new AppUser(); u34.Email = stru34Email; u34.UserName = stru34Email; u34.FirstName = "Sarah"; u34.LastName = "Saunders"; u34.MiddleInitial = "J"; u34.Address = "332 Avenue C"; u34.City = "Austin"; u34.State = StateAbrv.TX; u34.ZipCode = "78705"; u34.PhoneNumber = "5123497810"; u34.DOB = DateTime.Parse("10/29/1977");
            String stru35Email = "willsheff@email.com"; AppUser u35 = new AppUser(); u35.Email = stru35Email; u35.UserName = stru35Email; u35.FirstName = "William"; u35.LastName = "Sewell"; u35.MiddleInitial = "T"; u35.Address = "2365 51st St."; u35.City = "Austin"; u35.State = StateAbrv.TX; u35.ZipCode = "78709"; u35.PhoneNumber = "5124510084"; u35.DOB = DateTime.Parse("4/21/1941");
            String stru36Email = "sheff44@ggmail.com"; AppUser u36 = new AppUser(); u36.Email = stru36Email; u36.UserName = stru36Email; u36.FirstName = "Martin"; u36.LastName = "Sheffield"; u36.MiddleInitial = "J"; u36.Address = "3886 Avenue A"; u36.City = "Austin"; u36.State = StateAbrv.TX; u36.ZipCode = "78705"; u36.PhoneNumber = "5125479167"; u36.DOB = DateTime.Parse("11/10/1937");
            String stru37Email = "johnsmith187@aool.com"; AppUser u37 = new AppUser(); u37.Email = stru37Email; u37.UserName = stru37Email; u37.FirstName = "John"; u37.LastName = "Smith"; u37.MiddleInitial = "A"; u37.Address = "23 Hidden Forge Dr."; u37.City = "San Antonio"; u37.State = StateAbrv.TX; u37.ZipCode = "78280"; u37.PhoneNumber = "2108321888"; u37.DOB = DateTime.Parse("10/26/1954");
            String stru38Email = "dustroud@mail.com"; AppUser u38 = new AppUser(); u38.Email = stru38Email; u38.UserName = stru38Email; u38.FirstName = "Dustin"; u38.LastName = "Stroud"; u38.MiddleInitial = "P"; u38.Address = "1212 Rita Rd"; u38.City = "Dallas"; u38.State = StateAbrv.TX; u38.ZipCode = "75221"; u38.PhoneNumber = "2142346667"; u38.DOB = DateTime.Parse("9/1/1932");
            String stru39Email = "ericstuart@aool.com"; AppUser u39 = new AppUser(); u39.Email = stru39Email; u39.UserName = stru39Email; u39.FirstName = "Eric"; u39.LastName = "Stuart"; u39.MiddleInitial = "D"; u39.Address = "5576 Toro Ring"; u39.City = "Austin"; u39.State = StateAbrv.TX; u39.ZipCode = "78746"; u39.PhoneNumber = "5128178335"; u39.DOB = DateTime.Parse("12/28/1930");
            String stru40Email = "peterstump@hootmail.com"; AppUser u40 = new AppUser(); u40.Email = stru40Email; u40.UserName = stru40Email; u40.FirstName = "Peter"; u40.LastName = "Stump"; u40.MiddleInitial = "L"; u40.Address = "1300 Kellen Circle"; u40.City = "Houston"; u40.State = StateAbrv.TX; u40.ZipCode = "77018"; u40.PhoneNumber = "8174560903"; u40.DOB = DateTime.Parse("8/13/1989");
            String stru41Email = "tanner@ggmail.com"; AppUser u41 = new AppUser(); u41.Email = stru41Email; u41.UserName = stru41Email; u41.FirstName = "Jeremy"; u41.LastName = "Tanner"; u41.MiddleInitial = "S"; u41.Address = "4347 Almstead"; u41.City = "Houston"; u41.State = StateAbrv.TX; u41.ZipCode = "77044"; u41.PhoneNumber = "8174590929"; u41.DOB = DateTime.Parse("5/21/1982");
            String stru42Email = "taylordjay@aool.com"; AppUser u42 = new AppUser(); u42.Email = stru42Email; u42.UserName = stru42Email; u42.FirstName = "Allison"; u42.LastName = "Taylor"; u42.MiddleInitial = "R"; u42.Address = "467 Nueces St."; u42.City = "Austin"; u42.State = StateAbrv.TX; u42.ZipCode = "78705"; u42.PhoneNumber = "5124748452"; u42.DOB = DateTime.Parse("1/8/1960");
            String stru43Email = "TayTaylor@aool.com"; AppUser u43 = new AppUser(); u43.Email = stru43Email; u43.UserName = stru43Email; u43.FirstName = "Rachel"; u43.LastName = "Taylor"; u43.MiddleInitial = "K"; u43.Address = "345 Longview Dr."; u43.City = "Austin"; u43.State = StateAbrv.TX; u43.ZipCode = "78705"; u43.PhoneNumber = "5124512631"; u43.DOB = DateTime.Parse("7/27/1975");
            String stru44Email = "teefrank@hootmail.com"; AppUser u44 = new AppUser(); u44.Email = stru44Email; u44.UserName = stru44Email; u44.FirstName = "Frank"; u44.LastName = "Tee"; u44.MiddleInitial = "J"; u44.Address = "5590 Lavell Dr"; u44.City = "Houston"; u44.State = StateAbrv.TX; u44.ZipCode = "77004"; u44.PhoneNumber = "8178765543"; u44.DOB = DateTime.Parse("4/6/1968");
            String stru45Email = "tuck33@ggmail.com"; AppUser u45 = new AppUser(); u45.Email = stru45Email; u45.UserName = stru45Email; u45.FirstName = "Clent"; u45.LastName = "Tucker"; u45.MiddleInitial = "J"; u45.Address = "312 Main St."; u45.City = "Dallas"; u45.State = StateAbrv.TX; u45.ZipCode = "75315"; u45.PhoneNumber = "2148471154"; u45.DOB = DateTime.Parse("5/19/1978");
            String stru46Email = "avelasco@yaho.com"; AppUser u46 = new AppUser(); u46.Email = stru46Email; u46.UserName = stru46Email; u46.FirstName = "Allen"; u46.LastName = "Velasco"; u46.MiddleInitial = "G"; u46.Address = "679 W. 4th"; u46.City = "Dallas"; u46.State = StateAbrv.TX; u46.ZipCode = "75207"; u46.PhoneNumber = "2143985638"; u46.DOB = DateTime.Parse("1/4/1900");
            String stru47Email = "westj@pioneer.net"; AppUser u47 = new AppUser(); u47.Email = stru47Email; u47.UserName = stru47Email; u47.FirstName = "Jake"; u47.LastName = "West"; u47.MiddleInitial = "T"; u47.Address = "RR 3287"; u47.City = "Dallas"; u47.State = StateAbrv.TX; u47.ZipCode = "75323"; u47.PhoneNumber = "2148475244"; u47.DOB = DateTime.Parse("10/14/1993");
            String stru48Email = "louielouie@aool.com"; AppUser u48 = new AppUser(); u48.Email = stru48Email; u48.UserName = stru48Email; u48.FirstName = "Louis"; u48.LastName = "Winthorpe"; u48.MiddleInitial = "L"; u48.Address = "2500 Padre Blvd"; u48.City = "Dallas"; u48.State = StateAbrv.TX; u48.ZipCode = "75220"; u48.PhoneNumber = "2145650098"; u48.DOB = DateTime.Parse("5/31/1952");
            String stru49Email = "rwood@voyager.net"; AppUser u49 = new AppUser(); u49.Email = stru49Email; u49.UserName = stru49Email; u49.FirstName = "Reagan"; u49.LastName = "Wood"; u49.MiddleInitial = "B"; u49.Address = "447 Westlake Dr."; u49.City = "Austin"; u49.State = StateAbrv.TX; u49.ZipCode = "78746"; u49.PhoneNumber = "5124545242"; u49.DOB = DateTime.Parse("4/24/1992");


            AppUser userToAddu1 = userManager.FindByName(stru1Email); if (userToAddu1 == null) { userManager.Create(u1, "gazing"); userToAddu1 = db.Users.Single(u => u.Email == stru1Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu1.Id, roleName) == false) { userManager.AddToRole(userToAddu1.Id, roleName); } }
            AppUser userToAddu2 = userManager.FindByName(stru2Email); if (userToAddu2 == null) { userManager.Create(u2, "banquet"); userToAddu2 = db.Users.Single(u => u.Email == stru2Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu2.Id, roleName) == false) { userManager.AddToRole(userToAddu2.Id, roleName); } }
            AppUser userToAddu3 = userManager.FindByName(stru3Email); if (userToAddu3 == null) { userManager.Create(u3, "666666"); userToAddu3 = db.Users.Single(u => u.Email == stru3Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu3.Id, roleName) == false) { userManager.AddToRole(userToAddu3.Id, roleName); } }
            AppUser userToAddu4 = userManager.FindByName(stru4Email); if (userToAddu4 == null) { userManager.Create(u4, "clover"); userToAddu4 = db.Users.Single(u => u.Email == stru4Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu4.Id, roleName) == false) { userManager.AddToRole(userToAddu4.Id, roleName); } }
            AppUser userToAddu5 = userManager.FindByName(stru5Email); if (userToAddu5 == null) { userManager.Create(u5, "austin"); userToAddu5 = db.Users.Single(u => u.Email == stru5Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu5.Id, roleName) == false) { userManager.AddToRole(userToAddu5.Id, roleName); } }
            AppUser userToAddu6 = userManager.FindByName(stru6Email); if (userToAddu6 == null) { userManager.Create(u6, "mailbox"); userToAddu6 = db.Users.Single(u => u.Email == stru6Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu6.Id, roleName) == false) { userManager.AddToRole(userToAddu6.Id, roleName); } }
            AppUser userToAddu7 = userManager.FindByName(stru7Email); if (userToAddu7 == null) { userManager.Create(u7, "aggies"); userToAddu7 = db.Users.Single(u => u.Email == stru7Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu7.Id, roleName) == false) { userManager.AddToRole(userToAddu7.Id, roleName); } }
            AppUser userToAddu8 = userManager.FindByName(stru8Email); if (userToAddu8 == null) { userManager.Create(u8, "raiders"); userToAddu8 = db.Users.Single(u => u.Email == stru8Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu8.Id, roleName) == false) { userManager.AddToRole(userToAddu8.Id, roleName); } }
            AppUser userToAddu9 = userManager.FindByName(stru9Email); if (userToAddu9 == null) { userManager.Create(u9, "mustangs"); userToAddu9 = db.Users.Single(u => u.Email == stru9Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu9.Id, roleName) == false) { userManager.AddToRole(userToAddu9.Id, roleName); } }
            AppUser userToAddu10 = userManager.FindByName(stru10Email); if (userToAddu10 == null) { userManager.Create(u10, "region"); userToAddu10 = db.Users.Single(u => u.Email == stru10Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu10.Id, roleName) == false) { userManager.AddToRole(userToAddu10.Id, roleName); } }
            AppUser userToAddu11 = userManager.FindByName(stru11Email); if (userToAddu11 == null) { userManager.Create(u11, "hungry"); userToAddu11 = db.Users.Single(u => u.Email == stru11Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu11.Id, roleName) == false) { userManager.AddToRole(userToAddu11.Id, roleName); } }
            AppUser userToAddu12 = userManager.FindByName(stru12Email); if (userToAddu12 == null) { userManager.Create(u12, "logicon"); userToAddu12 = db.Users.Single(u => u.Email == stru12Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu12.Id, roleName) == false) { userManager.AddToRole(userToAddu12.Id, roleName); } }
            AppUser userToAddu13 = userManager.FindByName(stru13Email); if (userToAddu13 == null) { userManager.Create(u13, "doofus"); userToAddu13 = db.Users.Single(u => u.Email == stru13Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu13.Id, roleName) == false) { userManager.AddToRole(userToAddu13.Id, roleName); } }
            AppUser userToAddu14 = userManager.FindByName(stru14Email); if (userToAddu14 == null) { userManager.Create(u14, "mother"); userToAddu14 = db.Users.Single(u => u.Email == stru14Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu14.Id, roleName) == false) { userManager.AddToRole(userToAddu14.Id, roleName); } }
            AppUser userToAddu15 = userManager.FindByName(stru15Email); if (userToAddu15 == null) { userManager.Create(u15, "whimsical"); userToAddu15 = db.Users.Single(u => u.Email == stru15Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu15.Id, roleName) == false) { userManager.AddToRole(userToAddu15.Id, roleName); } }
            AppUser userToAddu16 = userManager.FindByName(stru16Email); if (userToAddu16 == null) { userManager.Create(u16, "nothing"); userToAddu16 = db.Users.Single(u => u.Email == stru16Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu16.Id, roleName) == false) { userManager.AddToRole(userToAddu16.Id, roleName); } }
            AppUser userToAddu17 = userManager.FindByName(stru17Email); if (userToAddu17 == null) { userManager.Create(u17, "GoodFellow"); userToAddu17 = db.Users.Single(u => u.Email == stru17Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu17.Id, roleName) == false) { userManager.AddToRole(userToAddu17.Id, roleName); } }
            AppUser userToAddu18 = userManager.FindByName(stru18Email); if (userToAddu18 == null) { userManager.Create(u18, "impede"); userToAddu18 = db.Users.Single(u => u.Email == stru18Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu18.Id, roleName) == false) { userManager.AddToRole(userToAddu18.Id, roleName); } }
            AppUser userToAddu19 = userManager.FindByName(stru19Email); if (userToAddu19 == null) { userManager.Create(u19, "LuceyDucey"); userToAddu19 = db.Users.Single(u => u.Email == stru19Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu19.Id, roleName) == false) { userManager.AddToRole(userToAddu19.Id, roleName); } }
            AppUser userToAddu20 = userManager.FindByName(stru20Email); if (userToAddu20 == null) { userManager.Create(u20, "cloudyday"); userToAddu20 = db.Users.Single(u => u.Email == stru20Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu20.Id, roleName) == false) { userManager.AddToRole(userToAddu20.Id, roleName); } }
            AppUser userToAddu21 = userManager.FindByName(stru21Email); if (userToAddu21 == null) { userManager.Create(u21, "emarkbark"); userToAddu21 = db.Users.Single(u => u.Email == stru21Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu21.Id, roleName) == false) { userManager.AddToRole(userToAddu21.Id, roleName); } }
            AppUser userToAddu22 = userManager.FindByName(stru22Email); if (userToAddu22 == null) { userManager.Create(u22, "smartinmartin"); userToAddu22 = db.Users.Single(u => u.Email == stru22Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu22.Id, roleName) == false) { userManager.AddToRole(userToAddu22.Id, roleName); } }
            AppUser userToAddu23 = userManager.FindByName(stru23Email); if (userToAddu23 == null) { userManager.Create(u23, "looter"); userToAddu23 = db.Users.Single(u => u.Email == stru23Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu23.Id, roleName) == false) { userManager.AddToRole(userToAddu23.Id, roleName); } }
            AppUser userToAddu24 = userManager.FindByName(stru24Email); if (userToAddu24 == null) { userManager.Create(u24, "chucky33"); userToAddu24 = db.Users.Single(u => u.Email == stru24Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu24.Id, roleName) == false) { userManager.AddToRole(userToAddu24.Id, roleName); } }
            AppUser userToAddu25 = userManager.FindByName(stru25Email); if (userToAddu25 == null) { userManager.Create(u25, "orange"); userToAddu25 = db.Users.Single(u => u.Email == stru25Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu25.Id, roleName) == false) { userManager.AddToRole(userToAddu25.Id, roleName); } }
            AppUser userToAddu26 = userManager.FindByName(stru26Email); if (userToAddu26 == null) { userManager.Create(u26, "victorious"); userToAddu26 = db.Users.Single(u => u.Email == stru26Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu26.Id, roleName) == false) { userManager.AddToRole(userToAddu26.Id, roleName); } }
            AppUser userToAddu27 = userManager.FindByName(stru27Email); if (userToAddu27 == null) { userManager.Create(u27, "billyboy"); userToAddu27 = db.Users.Single(u => u.Email == stru27Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu27.Id, roleName) == false) { userManager.AddToRole(userToAddu27.Id, roleName); } }
            AppUser userToAddu28 = userManager.FindByName(stru28Email); if (userToAddu28 == null) { userManager.Create(u28, "radicalone"); userToAddu28 = db.Users.Single(u => u.Email == stru28Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu28.Id, roleName) == false) { userManager.AddToRole(userToAddu28.Id, roleName); } }
            AppUser userToAddu29 = userManager.FindByName(stru29Email); if (userToAddu29 == null) { userManager.Create(u29, "gohorns"); userToAddu29 = db.Users.Single(u => u.Email == stru29Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu29.Id, roleName) == false) { userManager.AddToRole(userToAddu29.Id, roleName); } }
            AppUser userToAddu30 = userManager.FindByName(stru30Email); if (userToAddu30 == null) { userManager.Create(u30, "iloveme"); userToAddu30 = db.Users.Single(u => u.Email == stru30Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu30.Id, roleName) == false) { userManager.AddToRole(userToAddu30.Id, roleName); } }
            AppUser userToAddu31 = userManager.FindByName(stru31Email); if (userToAddu31 == null) { userManager.Create(u31, "greedy"); userToAddu31 = db.Users.Single(u => u.Email == stru31Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu31.Id, roleName) == false) { userManager.AddToRole(userToAddu31.Id, roleName); } }
            AppUser userToAddu32 = userManager.FindByName(stru32Email); if (userToAddu32 == null) { userManager.Create(u32, "familiar"); userToAddu32 = db.Users.Single(u => u.Email == stru32Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu32.Id, roleName) == false) { userManager.AddToRole(userToAddu32.Id, roleName); } }
            AppUser userToAddu33 = userManager.FindByName(stru33Email); if (userToAddu33 == null) { userManager.Create(u33, "historical"); userToAddu33 = db.Users.Single(u => u.Email == stru33Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu33.Id, roleName) == false) { userManager.AddToRole(userToAddu33.Id, roleName); } }
            AppUser userToAddu34 = userManager.FindByName(stru34Email); if (userToAddu34 == null) { userManager.Create(u34, "guiltless"); userToAddu34 = db.Users.Single(u => u.Email == stru34Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu34.Id, roleName) == false) { userManager.AddToRole(userToAddu34.Id, roleName); } }
            AppUser userToAddu35 = userManager.FindByName(stru35Email); if (userToAddu35 == null) { userManager.Create(u35, "frequent"); userToAddu35 = db.Users.Single(u => u.Email == stru35Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu35.Id, roleName) == false) { userManager.AddToRole(userToAddu35.Id, roleName); } }
            AppUser userToAddu36 = userManager.FindByName(stru36Email); if (userToAddu36 == null) { userManager.Create(u36, "history"); userToAddu36 = db.Users.Single(u => u.Email == stru36Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu36.Id, roleName) == false) { userManager.AddToRole(userToAddu36.Id, roleName); } }
            AppUser userToAddu37 = userManager.FindByName(stru37Email); if (userToAddu37 == null) { userManager.Create(u37, "squirrel"); userToAddu37 = db.Users.Single(u => u.Email == stru37Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu37.Id, roleName) == false) { userManager.AddToRole(userToAddu37.Id, roleName); } }
            AppUser userToAddu38 = userManager.FindByName(stru38Email); if (userToAddu38 == null) { userManager.Create(u38, "snakes"); userToAddu38 = db.Users.Single(u => u.Email == stru38Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu38.Id, roleName) == false) { userManager.AddToRole(userToAddu38.Id, roleName); } }
            AppUser userToAddu39 = userManager.FindByName(stru39Email); if (userToAddu39 == null) { userManager.Create(u39, "landus"); userToAddu39 = db.Users.Single(u => u.Email == stru39Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu39.Id, roleName) == false) { userManager.AddToRole(userToAddu39.Id, roleName); } }
            AppUser userToAddu40 = userManager.FindByName(stru40Email); if (userToAddu40 == null) { userManager.Create(u40, "rhythm"); userToAddu40 = db.Users.Single(u => u.Email == stru40Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu40.Id, roleName) == false) { userManager.AddToRole(userToAddu40.Id, roleName); } }
            AppUser userToAddu41 = userManager.FindByName(stru41Email); if (userToAddu41 == null) { userManager.Create(u41, "kindly"); userToAddu41 = db.Users.Single(u => u.Email == stru41Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu41.Id, roleName) == false) { userManager.AddToRole(userToAddu41.Id, roleName); } }
            AppUser userToAddu42 = userManager.FindByName(stru42Email); if (userToAddu42 == null) { userManager.Create(u42, "instrument"); userToAddu42 = db.Users.Single(u => u.Email == stru42Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu42.Id, roleName) == false) { userManager.AddToRole(userToAddu42.Id, roleName); } }
            AppUser userToAddu43 = userManager.FindByName(stru43Email); if (userToAddu43 == null) { userManager.Create(u43, "arched"); userToAddu43 = db.Users.Single(u => u.Email == stru43Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu43.Id, roleName) == false) { userManager.AddToRole(userToAddu43.Id, roleName); } }
            AppUser userToAddu44 = userManager.FindByName(stru44Email); if (userToAddu44 == null) { userManager.Create(u44, "median"); userToAddu44 = db.Users.Single(u => u.Email == stru44Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu44.Id, roleName) == false) { userManager.AddToRole(userToAddu44.Id, roleName); } }
            AppUser userToAddu45 = userManager.FindByName(stru45Email); if (userToAddu45 == null) { userManager.Create(u45, "approval"); userToAddu45 = db.Users.Single(u => u.Email == stru45Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu45.Id, roleName) == false) { userManager.AddToRole(userToAddu45.Id, roleName); } }
            AppUser userToAddu46 = userManager.FindByName(stru46Email); if (userToAddu46 == null) { userManager.Create(u46, "decorate"); userToAddu46 = db.Users.Single(u => u.Email == stru46Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu46.Id, roleName) == false) { userManager.AddToRole(userToAddu46.Id, roleName); } }
            AppUser userToAddu47 = userManager.FindByName(stru47Email); if (userToAddu47 == null) { userManager.Create(u47, "grover"); userToAddu47 = db.Users.Single(u => u.Email == stru47Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu47.Id, roleName) == false) { userManager.AddToRole(userToAddu47.Id, roleName); } }
            AppUser userToAddu48 = userManager.FindByName(stru48Email); if (userToAddu48 == null) { userManager.Create(u48, "sturdy"); userToAddu48 = db.Users.Single(u => u.Email == stru48Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu48.Id, roleName) == false) { userManager.AddToRole(userToAddu48.Id, roleName); } }
            AppUser userToAddu49 = userManager.FindByName(stru49Email); if (userToAddu49 == null) { userManager.Create(u49, "decorous"); userToAddu49 = db.Users.Single(u => u.Email == stru49Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu49.Id, roleName) == false) { userManager.AddToRole(userToAddu49.Id, roleName); } }

            String stru50Email = "t.jacobs@longhornbank.neet"; AppUser u50 = new AppUser(); u50.Email = stru50Email; u50.UserName = stru50Email; u50.EmpType = EmpType.Employee; u50.FirstName = "Todd"; u50.LastName = "Jacobs"; u50.MiddleInitial = "L"; u50.Address = "4564 Elm St."; u50.City = "Houston"; u50.State = StateAbrv.TX; u50.ZipCode = "77003"; u50.PhoneNumber = "8176593544"; u50.DOB = DateTime.Parse("1/1/1900"); u50.SSN = "222222222";
            String stru51Email = "e.rice@longhornbank.neet"; AppUser u51 = new AppUser(); u51.Email = stru51Email; u51.UserName = stru51Email; u51.EmpType = EmpType.Employee; u51.FirstName = "Eryn"; u51.LastName = "Rice"; u51.MiddleInitial = "M"; u51.Address = "3405 Rio Grande"; u51.City = "Dallas"; u51.State = StateAbrv.TX; u51.ZipCode = "75261"; u51.PhoneNumber = "2148475583"; u51.DOB = DateTime.Parse("1/1/1900"); u51.SSN = "111111111"; ;
            String stru52Email = "b.ingram@longhornbank.neet"; AppUser u52 = new AppUser(); u52.Email = stru52Email; u52.UserName = stru52Email; u52.EmpType = EmpType.Employee; u52.FirstName = "Brad"; u52.LastName = "Ingram"; u52.MiddleInitial = "S"; u52.Address = "6548 La Posada Ct."; u52.City = "Austin"; u52.State = StateAbrv.TX; u52.ZipCode = "78705"; u52.PhoneNumber = "5126978613"; u52.DOB = DateTime.Parse("1/1/1900"); u52.SSN = "545454545";
            String stru54Email = "g.martinez@longhornbank.neet"; AppUser u54 = new AppUser(); u54.Email = stru54Email; u54.UserName = stru54Email; u54.EmpType = EmpType.Employee; u54.FirstName = "Gregory"; u54.LastName = "Martinez"; u54.MiddleInitial = "R"; u54.Address = "8295 Sunset Blvd."; u54.City = "San Antonio"; u54.State = StateAbrv.TX; u54.ZipCode = "78239"; u54.PhoneNumber = "2105788965"; u54.DOB = DateTime.Parse("1/1/1900"); u54.SSN = "574677829";
            String stru57Email = "j.tanner@longhornbank.neet"; AppUser u57 = new AppUser(); u57.Email = stru57Email; u57.UserName = stru57Email; u57.EmpType = EmpType.Employee; u57.FirstName = "Jeremy"; u57.LastName = "Tanner"; u57.MiddleInitial = "S"; u57.Address = "4347 Almstead"; u57.City = "Austin"; u57.State = StateAbrv.TX; u57.ZipCode = "78761"; u57.PhoneNumber = "5129457399"; u57.DOB = DateTime.Parse("1/1/1900"); u57.SSN = "888887878";
            String stru60Email = "l.chung@longhornbank.neet"; AppUser u60 = new AppUser(); u60.Email = stru60Email; u60.UserName = stru60Email; u60.EmpType = EmpType.Employee; u60.FirstName = "Lisa"; u60.LastName = "Chung"; u60.MiddleInitial = "N"; u60.Address = "234 RR 12"; u60.City = "San Antonio"; u60.State = StateAbrv.TX; u60.ZipCode = "78268"; u60.PhoneNumber = "2106983548"; u60.DOB = DateTime.Parse("1/1/1900"); u60.SSN = "333333333";
            String stru62Email = "w.loter@longhornbank.neet"; AppUser u62 = new AppUser(); u62.Email = stru62Email; u62.UserName = stru62Email; u62.EmpType = EmpType.Employee; u62.FirstName = "Wanda"; u62.LastName = "Loter"; u62.MiddleInitial = "K"; u62.Address = "3453 RR 3235"; u62.City = "Austin"; u62.State = StateAbrv.TX; u62.ZipCode = "78732"; u62.PhoneNumber = "5124579845"; u62.DOB = DateTime.Parse("1/1/1900"); u62.SSN = "555555555";
            String stru65Email = "h.morales@longhornbank.neet"; AppUser u65 = new AppUser(); u65.Email = stru65Email; u65.UserName = stru65Email; u65.EmpType = EmpType.Employee; u65.FirstName = "Hector"; u65.LastName = "Morales"; u65.MiddleInitial = "N"; u65.Address = "4501 RR 140"; u65.City = "Houston"; u65.State = StateAbrv.TX; u65.ZipCode = "77031"; u65.PhoneNumber = "8177458615"; u65.DOB = DateTime.Parse("1/1/1900"); u65.SSN = "898989898";
            String stru66Email = "m.rankin@longhornbank.neet"; AppUser u66 = new AppUser(); u66.Email = stru66Email; u66.UserName = stru66Email; u66.EmpType = EmpType.Employee; u66.FirstName = "Mary"; u66.LastName = "Rankin"; u66.MiddleInitial = "T"; u66.Address = "340 Second St"; u66.City = "Austin"; u66.State = StateAbrv.TX; u66.ZipCode = "78703"; u66.PhoneNumber = "5122926966"; u66.DOB = DateTime.Parse("1/1/1900"); u66.SSN = "999888777";
            String stru69Email = "g.gonzalez@longhornbank.neet"; AppUser u69 = new AppUser(); u69.Email = stru69Email; u69.UserName = stru69Email; u69.EmpType = EmpType.Employee; u69.FirstName = "Gwen"; u69.LastName = "Gonzalez"; u69.MiddleInitial = "J"; u69.Address = "103 Manor Rd"; u69.City = "Dallas"; u69.State = StateAbrv.TX; u69.ZipCode = "75260"; u69.PhoneNumber = "2142345566"; u69.DOB = DateTime.Parse("1/1/1900"); u69.SSN = "499551454";
            String stru53Email = "a.taylor@longhornbank.neet"; AppUser u53 = new AppUser(); u53.Email = stru53Email; u53.UserName = stru53Email; u53.EmpType = EmpType.Manager; u53.FirstName = "Allison"; u53.LastName = "Taylor"; u53.MiddleInitial = "R"; u53.Address = "467 Nueces St."; u53.City = "Dallas"; u53.State = StateAbrv.TX; u53.ZipCode = "75237"; u53.PhoneNumber = "2148965621"; u53.DOB = DateTime.Parse("1/1/1900"); u53.SSN = "645889563";
            String stru55Email = "m.sheffield@longhornbank.neet"; AppUser u55 = new AppUser(); u55.Email = stru55Email; u55.UserName = stru55Email; u55.EmpType = EmpType.Manager; u55.FirstName = "Martin"; u55.LastName = "Sheffield"; u55.MiddleInitial = "J"; u55.Address = "3886 Avenue A"; u55.City = "Austin"; u55.State = StateAbrv.TX; u55.ZipCode = "78736"; u55.PhoneNumber = "5124678821"; u55.DOB = DateTime.Parse("1/1/1900"); u55.SSN = "334557278";
            String stru56Email = "j.macleod@longhornbank.neet"; AppUser u56 = new AppUser(); u56.Email = stru56Email; u56.UserName = stru56Email; u56.EmpType = EmpType.Manager; u56.FirstName = "Jennifer"; u56.LastName = "MacLeod"; u56.MiddleInitial = "D"; u56.Address = "2504 Far West Blvd."; u56.City = "Austin"; u56.State = StateAbrv.TX; u56.ZipCode = "78731"; u56.PhoneNumber = "5124653365"; u56.DOB = DateTime.Parse("1/1/1900"); u56.SSN = "886719249";
            String stru58Email = "m.rhodes@longhornbank.neet"; AppUser u58 = new AppUser(); u58.Email = stru58Email; u58.UserName = stru58Email; u58.EmpType = EmpType.Manager; u58.FirstName = "Megan"; u58.LastName = "Rhodes"; u58.MiddleInitial = "C"; u58.Address = "4587 Enfield Rd."; u58.City = "San Antonio"; u58.State = StateAbrv.TX; u58.ZipCode = "78293"; u58.PhoneNumber = "2102449976"; u58.DOB = DateTime.Parse("1/1/1900"); u58.SSN = "999990909";
            String stru59Email = "e.stuart@longhornbank.neet"; AppUser u59 = new AppUser(); u59.Email = stru59Email; u59.UserName = stru59Email; u59.EmpType = EmpType.Manager; u59.FirstName = "Eric"; u59.LastName = "Stuart"; u59.MiddleInitial = "F"; u59.Address = "5576 Toro Ring"; u59.City = "San Antonio"; u59.State = StateAbrv.TX; u59.ZipCode = "78279"; u59.PhoneNumber = "2105344627"; u59.DOB = DateTime.Parse("1/1/1900"); u59.SSN = "212121212";
            String stru61Email = "l.swanson@longhornbank.neet"; AppUser u61 = new AppUser(); u61.Email = stru61Email; u61.UserName = stru61Email; u61.EmpType = EmpType.Manager; u61.FirstName = "Leon"; u61.LastName = "Swanson"; u61.MiddleInitial = ""; u61.Address = "245 River Rd"; u61.City = "Austin"; u61.State = StateAbrv.TX; u61.ZipCode = "78731"; u61.PhoneNumber = "5124748138"; u61.DOB = DateTime.Parse("1/1/1900"); u61.SSN = "444444444";
            String stru63Email = "j.white@longhornbank.neet"; AppUser u63 = new AppUser(); u63.Email = stru63Email; u63.UserName = stru63Email; u63.EmpType = EmpType.Manager; u63.FirstName = "Jason"; u63.LastName = "White"; u63.MiddleInitial = "M"; u63.Address = "12 Valley View"; u63.City = "Houston"; u63.State = StateAbrv.TX; u63.ZipCode = "77045"; u63.PhoneNumber = "8174955201"; u63.DOB = DateTime.Parse("1/1/1900"); u63.SSN = "666666666";
            String stru64Email = "w.montgomery@longhornbank.neet"; AppUser u64 = new AppUser(); u64.Email = stru64Email; u64.UserName = stru64Email; u64.EmpType = EmpType.Manager; u64.FirstName = "Wilda"; u64.LastName = "Montgomery"; u64.MiddleInitial = "K"; u64.Address = "210 Blanco Dr"; u64.City = "Houston"; u64.State = StateAbrv.TX; u64.ZipCode = "77030"; u64.PhoneNumber = "8178746718"; u64.DOB = DateTime.Parse("1/1/1900"); u64.SSN = "676767676";
            String stru67Email = "l.walker@longhornbank.neet"; AppUser u67 = new AppUser(); u67.Email = stru67Email; u67.UserName = stru67Email; u67.EmpType = EmpType.Manager; u67.FirstName = "Larry"; u67.LastName = "Walker"; u67.MiddleInitial = "G"; u67.Address = "9 Bison Circle"; u67.City = "Dallas"; u67.State = StateAbrv.TX; u67.ZipCode = "75238"; u67.PhoneNumber = "2143125897"; u67.DOB = DateTime.Parse("1/1/1900"); u67.SSN = "323232323";
            String stru68Email = "g.chang@longhornbank.neet"; AppUser u68 = new AppUser(); u68.Email = stru68Email; u68.UserName = stru68Email; u68.EmpType = EmpType.Manager; u68.FirstName = "George"; u68.LastName = "Chang"; u68.MiddleInitial = "M"; u68.Address = "9003 Joshua St"; u68.City = "San Antonio"; u68.State = StateAbrv.TX; u68.ZipCode = "78260"; u68.PhoneNumber = "2103450925"; u68.DOB = DateTime.Parse("1/1/1900"); u68.SSN = "111222233";

            AppUser userToAddu50 = userManager.FindByName(stru50Email); if (userToAddu50 == null) { userManager.Create(u50, "society"); userToAddu50 = db.Users.Single(u => u.Email == stru50Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu50.Id, Employee) == false) { userManager.AddToRole(userToAddu50.Id, Employee); } }
            AppUser userToAddu51 = userManager.FindByName(stru51Email); if (userToAddu51 == null) { userManager.Create(u51, "ricearoni"); userToAddu51 = db.Users.Single(u => u.Email == stru51Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu51.Id, Employee) == false) { userManager.AddToRole(userToAddu51.Id, Employee); } }
            AppUser userToAddu52 = userManager.FindByName(stru52Email); if (userToAddu52 == null) { userManager.Create(u52, "ingram45"); userToAddu52 = db.Users.Single(u => u.Email == stru52Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu52.Id, Employee) == false) { userManager.AddToRole(userToAddu52.Id, Employee); } }
            AppUser userToAddu54 = userManager.FindByName(stru54Email); if (userToAddu54 == null) { userManager.Create(u54, "fungus"); userToAddu54 = db.Users.Single(u => u.Email == stru54Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu54.Id, Employee) == false) { userManager.AddToRole(userToAddu54.Id, Employee); } }
            AppUser userToAddu57 = userManager.FindByName(stru57Email); if (userToAddu57 == null) { userManager.Create(u57, "tanman"); userToAddu57 = db.Users.Single(u => u.Email == stru57Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu57.Id, Employee) == false) { userManager.AddToRole(userToAddu57.Id, Employee); } }
            AppUser userToAddu60 = userManager.FindByName(stru60Email); if (userToAddu60 == null) { userManager.Create(u60, "lisssa"); userToAddu60 = db.Users.Single(u => u.Email == stru60Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu60.Id, Employee) == false) { userManager.AddToRole(userToAddu60.Id, Employee); } }
            AppUser userToAddu62 = userManager.FindByName(stru62Email); if (userToAddu62 == null) { userManager.Create(u62, "lottery"); userToAddu62 = db.Users.Single(u => u.Email == stru62Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu62.Id, Employee) == false) { userManager.AddToRole(userToAddu62.Id, Employee); } }
            AppUser userToAddu65 = userManager.FindByName(stru65Email); if (userToAddu65 == null) { userManager.Create(u65, "hecktour"); userToAddu65 = db.Users.Single(u => u.Email == stru65Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu65.Id, Employee) == false) { userManager.AddToRole(userToAddu65.Id, Employee); } }
            AppUser userToAddu66 = userManager.FindByName(stru66Email); if (userToAddu66 == null) { userManager.Create(u66, "rankmary"); userToAddu66 = db.Users.Single(u => u.Email == stru66Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu66.Id, Employee) == false) { userManager.AddToRole(userToAddu66.Id, Employee); } }
            AppUser userToAddu69 = userManager.FindByName(stru69Email); if (userToAddu69 == null) { userManager.Create(u69, "offbeat"); userToAddu69 = db.Users.Single(u => u.Email == stru69Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu69.Id, Employee) == false) { userManager.AddToRole(userToAddu69.Id, Employee); } }
            AppUser userToAddu53 = userManager.FindByName(stru53Email); if (userToAddu53 == null) { userManager.Create(u53, "society"); userToAddu53 = db.Users.Single(u => u.Email == stru53Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu53.Id, Manager) == false) { userManager.AddToRole(userToAddu53.Id, Manager); } }
            AppUser userToAddu55 = userManager.FindByName(stru55Email); if (userToAddu55 == null) { userManager.Create(u55, "ricearoni"); userToAddu55 = db.Users.Single(u => u.Email == stru55Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu55.Id, Manager) == false) { userManager.AddToRole(userToAddu55.Id, Manager); } }
            AppUser userToAddu56 = userManager.FindByName(stru56Email); if (userToAddu56 == null) { userManager.Create(u56, "ingram45"); userToAddu56 = db.Users.Single(u => u.Email == stru56Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu56.Id, Manager) == false) { userManager.AddToRole(userToAddu56.Id, Manager); } }
            AppUser userToAddu58 = userManager.FindByName(stru58Email); if (userToAddu58 == null) { userManager.Create(u58, "fungus"); userToAddu58 = db.Users.Single(u => u.Email == stru58Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu58.Id, Manager) == false) { userManager.AddToRole(userToAddu58.Id, Manager); } }
            AppUser userToAddu59 = userManager.FindByName(stru59Email); if (userToAddu59 == null) { userManager.Create(u59, "tanman"); userToAddu59 = db.Users.Single(u => u.Email == stru59Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu59.Id, Manager) == false) { userManager.AddToRole(userToAddu59.Id, Manager); } }
            AppUser userToAddu61 = userManager.FindByName(stru61Email); if (userToAddu61 == null) { userManager.Create(u61, "lisssa"); userToAddu61 = db.Users.Single(u => u.Email == stru61Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu61.Id, Manager) == false) { userManager.AddToRole(userToAddu61.Id, Manager); } }
            AppUser userToAddu63 = userManager.FindByName(stru63Email); if (userToAddu63 == null) { userManager.Create(u63, "lottery"); userToAddu63 = db.Users.Single(u => u.Email == stru63Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu63.Id, Manager) == false) { userManager.AddToRole(userToAddu63.Id, Manager); } }
            AppUser userToAddu64 = userManager.FindByName(stru64Email); if (userToAddu64 == null) { userManager.Create(u64, "hecktour"); userToAddu64 = db.Users.Single(u => u.Email == stru64Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu64.Id, Manager) == false) { userManager.AddToRole(userToAddu64.Id, Manager); } }
            AppUser userToAddu67 = userManager.FindByName(stru67Email); if (userToAddu67 == null) { userManager.Create(u67, "rankmary"); userToAddu67 = db.Users.Single(u => u.Email == stru67Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu67.Id, Manager) == false) { userManager.AddToRole(userToAddu67.Id, Manager); } }
            AppUser userToAddu68 = userManager.FindByName(stru68Email); if (userToAddu68 == null) { userManager.Create(u68, "offbeat"); userToAddu68 = db.Users.Single(u => u.Email == stru68Email); db.SaveChanges(); if (userManager.IsInRole(userToAddu68.Id, Manager) == false) { userManager.AddToRole(userToAddu68.Id, Manager); } }




        }
    }
}

