using Longhorn_Bank.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Longhorn_Bank.Migrations
{
    public static class UserData
    {
        public static AppDbContext db = new AppDbContext();
        public static void SeedUsers (AppDbContext db)
        {

            AppUser u1 = new AppUser() { Email = "cbaker@freezing.co.uk", PasswordHash = "gazing", FirstName = "Christopher", LastName = "Baker", MiddleInitial = "L", Address = "1245 Lake Austin Blvd.", City = "Austin", State = "TX", ZipCode = "78733", PhoneNumber = "5125571146", DOB = "33276" }; db.Users.AddOrUpdate(u => U.Email, u1);
            AppUser u2 = new User() { Email = "mb@aool.com", PasswordHash = "ban2102678873uet", FirstName = "Michelle", LastName = "Banks", MiddleInitial = "", Address = "1300 Tall Pine Lane", City = "San Antonio", State = "TX", ZipCode = "78261", Phone = "2102678873", DOB = "33047" }; db.Users.AddOrUpdate(u => U.Email, u2);
            AppUser u3 = new User() { Email = "fd@aool.com", PasswordHash = "666666", FirstName = "Franco", LastName = "Broccolo", MiddleInitial = "V", Address = "62 Browning Rd", City = "Houston", State = "TX", ZipCode = "77019", Phone = "8175659699", DOB = "31538" }; db.Users.AddOrUpdate(u => U.Email, u3);
            AppUser u4 = new User() { Email = "wendy@ggmail.com", PasswordHash = "clover", FirstName = "Wendy", LastName = "Chang", MiddleInitial = "L", Address = "202 Bellmont Hall", City = "Austin", State = "TX", ZipCode = "78713", Phone = "5125943222", DOB = "23732" }; db.Users.AddOrUpdate(u => U.Email, u4);
            AppUser u5 = new User() { Email = "limchou@yaho.com", PasswordHash = "austin", FirstName = "Lim", LastName = "Chou", MiddleInitial = "", Address = "1600 Teresa Lane", City = "San Antonio", State = "TX", ZipCode = "78266", Phone = "2107724599", DOB = "18428" }; db.Users.AddOrUpdate(u => U.Email, u5);
            AppUser u6 = new User() { Email = "Dixon@aool.com", PasswordHash = "mailbox", FirstName = "Shan", LastName = "Dixon", MiddleInitial = "D", Address = "234 Holston Circle", City = "Dallas", State = "TX", ZipCode = "75208", Phone = "2142643255", DOB = "11087" }; db.Users.AddOrUpdate(u => U.Email, u6);
            AppUser u7 = new User() { Email = "louann@ggmail.com", PasswordHash = "aggies", FirstName = "Lou Ann", LastName = "Feeley", MiddleInitial = "K", Address = "600 S 8th Street W", City = "Houston", State = "TX", ZipCode = "77010", Phone = "8172556749", DOB = "11013" }; db.Users.AddOrUpdate(u => U.Email, u7);
            AppUser u8 = new User() { Email = "tfreeley@minntonka.ci.state.mn.us", PasswordHash = "raiders", FirstName = "Tesa", LastName = "Freeley", MiddleInitial = "P", Address = "4448 Fairview Ave.", City = "Houston", State = "TX", ZipCode = "77009", Phone = "8173255687", DOB = "13028" }; db.Users.AddOrUpdate(u => U.Email, u8);
            AppUser u9 = new User() { Email = "mgar@aool.com", PasswordHash = "mustangs", FirstName = "Margaret", LastName = "Garcia", MiddleInitial = "L", Address = "594 Longview", City = "Houston", State = "TX", ZipCode = "77003", Phone = "8176593544", DOB = "33057" }; db.Users.AddOrUpdate(u => U.Email, u9);
            AppUser u10 = new User() { Email = "chaley@thug.com", PasswordHash = "region", FirstName = "Charles", LastName = "Haley", MiddleInitial = "E", Address = "One Cowboy Pkwy", City = "Dallas", State = "TX", ZipCode = "75261", Phone = "2148475583", DOB = "31307" }; db.Users.AddOrUpdate(u => U.Email, u10);
            AppUser u11 = new User() { Email = "34722eff@ggmail.com", PasswordHash = "hungry", FirstName = "Jeffrey", LastName = "Hampton", MiddleInitial = "T", Address = "337 38th St.", City = "Austin", State = "TX", ZipCode = "78705", Phone = "5126978613", DOB = "34722" }; db.Users.AddOrUpdate(u => U.Email, u11);
            AppUser u12 = new User() { Email = "w34342hearniii@umch.edu", PasswordHash = "logicon", FirstName = "John", LastName = "Hearn", MiddleInitial = "B", Address = "4225 North First", City = "Dallas", State = "TX", ZipCode = "75237", Phone = "2148965621", DOB = "34342" }; db.Users.AddOrUpdate(u => U.Email, u12);
            AppUser u13 = new User() { Email = "hicks43@ggmail.com", PasswordHash = "doofus", FirstName = "Anthony", LastName = "Hicks", MiddleInitial = "J", Address = "32 NE Garden Ln., Ste 910", City = "San Antonio", State = "TX", ZipCode = "78239", Phone = "2105788965", DOB = "33152" }; db.Users.AddOrUpdate(u => U.Email, u13);
            AppUser u14 = new User() { Email = "bradsingram@mall.utexas.edu", PasswordHash = "mother", FirstName = "Brad", LastName = "Ingram", MiddleInitial = "S", Address = "6548 La Posada Ct.", City = "Austin", State = "TX", ZipCode = "78736", Phone = "5124678821", DOB = "30784" }; db.Users.AddOrUpdate(u => U.Email, u14);
            AppUser u15 = new User() { Email = "mother.Ingram@aool.com", PasswordHash = "whimsical", FirstName = "Todd", LastName = "Jacobs", MiddleInitial = "L", Address = "4564 Elm St.", City = "Austin", State = "TX", ZipCode = "78731", Phone = "5124653365", DOB = "30410" }; db.Users.AddOrUpdate(u => U.Email, u15);
            AppUser u16 = new User() { Email = "victoria@aool.com", PasswordHash = "nothing", FirstName = "Victoria", LastName = "Lawrence", MiddleInitial = "M", Address = "6639 Butterfly Ln.", City = "Austin", State = "TX", ZipCode = "78761", Phone = "5129457399", DOB = "22315" }; db.Users.AddOrUpdate(u => U.Email, u16);
            AppUser u17 = new User() { Email = "lineback@flush.net", PasswordHash = "GoodFellow", FirstName = "Erik", LastName = "Lineback", MiddleInitial = "W", Address = "1300 Netherland St", City = "San Antonio", State = "TX", ZipCode = "78293", Phone = "2102449976", DOB = "17048" }; db.Users.AddOrUpdate(u => U.Email, u17);
            AppUser u18 = new User() { Email = "elowe@netscrape.net", PasswordHash = "impede", FirstName = "Ernest", LastName = "Lowe", MiddleInitial = "S", Address = "3201 Pine Drive", City = "San Antonio", State = "TX", ZipCode = "78279", Phone = "2105344627", DOB = "33641" }; db.Users.AddOrUpdate(u => U.Email, u18);
            AppUser u19 = new User() { Email = "luce_chuck@ggmail.com", PasswordHash = "LuceyDucey", FirstName = "Chuck", LastName = "Luce", MiddleInitial = "B", Address = "2345 Rolling Clouds", City = "San Antonio", State = "TX", ZipCode = "78268", Phone = "2106983548", DOB = "15639" }; db.Users.AddOrUpdate(u => U.Email, u19);
            AppUser u20 = new User() { Email = "mackcloud@pimpdaddy.com", PasswordHash = "cloudyday", FirstName = "Jennifer", LastName = "MacLeod", MiddleInitial = "D", Address = "2504 Far West Blvd.", City = "Austin", State = "TX", ZipCode = "78731", Phone = "5124748138", DOB = "23960" }; db.Users.AddOrUpdate(u => U.Email, u20);
            AppUser u21 = new User() { Email = "liz@ggmail.com", PasswordHash = "emarkbark", FirstName = "Elizabeth", LastName = "Markham", MiddleInitial = "P", Address = "7861 Chevy Chase", City = "Austin", State = "TX", ZipCode = "78732", Phone = "5124579845", DOB = "21653" }; db.Users.AddOrUpdate(u => U.Email, u21);
            AppUser u22 = new User() { Email = "mclarence@aool.com", PasswordHash = "smartinmartin", FirstName = "Clarence", LastName = "Martin", MiddleInitial = "A", Address = "87 Alcedo St.", City = "Houston", State = "TX", ZipCode = "77045", Phone = "8174955201", DOB = "32879" }; db.Users.AddOrUpdate(u => U.Email, u22);
            AppUser u23 = new User() { Email = "smartinmartin.Martin@aool.com", PasswordHash = "looter", FirstName = "Gregory", LastName = "Martinez", MiddleInitial = "R", Address = "8295 Sunset Blvd.", City = "Houston", State = "TX", ZipCode = "77030", Phone = "8178746718", DOB = "32059" }; db.Users.AddOrUpdate(u => U.Email, u23);
            AppUser u24 = new User() { Email = "cmiller@mapster.com", PasswordHash = "chucky33", FirstName = "Charles", LastName = "Miller", MiddleInitial = "R", Address = "8962 Main St.", City = "Houston", State = "TX", ZipCode = "77031", Phone = "8177458615", DOB = "30884" }; db.Users.AddOrUpdate(u => U.Email, u24);
            AppUser u25 = new User() { Email = "nelson.Kelly@aool.com", PasswordHash = "orange", FirstName = "Kelly", LastName = "Nelson", MiddleInitial = "T", Address = "2601 Red River", City = "Austin", State = "TX", ZipCode = "78703", Phone = "5122926966", DOB = "20640" }; db.Users.AddOrUpdate(u => U.Email, u25);
            AppUser u26 = new User() { Email = "23040o23040oe@ggmail.com", PasswordHash = "victorious", FirstName = "Joe", LastName = "Nguyen", MiddleInitial = "C", Address = "1249 4th SW St.", City = "Dallas", State = "TX", ZipCode = "75238", Phone = "2143125897", DOB = "23040" }; db.Users.AddOrUpdate(u => U.Email, u26);
            AppUser u27 = new User() { Email = "orielly@foxnets.com", PasswordHash = "billyboy", FirstName = "Bill", LastName = "O'Reilly", MiddleInitial = "T", Address = "8800 Gringo Drive", City = "San Antonio", State = "TX", ZipCode = "78260", Phone = "2103450925", DOB = "30323" }; db.Users.AddOrUpdate(u => U.Email, u27);
            AppUser u28 = new User() { Email = "or@aool.com", PasswordHash = "radicalone", FirstName = "Anka", LastName = "Radkovich", MiddleInitial = "L", Address = "1300 Elliott Pl", City = "Dallas", State = "TX", ZipCode = "75260", Phone = "2142345566", DOB = "29311" }; db.Users.AddOrUpdate(u => U.Email, u28);
            AppUser u29 = new User() { Email = "megrhodes@freezing.co.uk", PasswordHash = "gohorns", FirstName = "Megan", LastName = "Rhodes", MiddleInitial = "C", Address = "4587 Enfield Rd.", City = "Austin", State = "TX", ZipCode = "78707", Phone = "5123744746", DOB = "16296" }; db.Users.AddOrUpdate(u => U.Email, u29);
            AppUser u30 = new User() { Email = "erynrice@aool.com", PasswordHash = "iloveme", FirstName = "Eryn", LastName = "Rice", MiddleInitial = "M", Address = "3405 Rio Grande", City = "Austin", State = "TX", ZipCode = "78705", Phone = "5123876657", DOB = "12633" }; db.Users.AddOrUpdate(u => U.Email, u30);
            AppUser u31 = new User() { Email = "32731orge@hootmail.com", PasswordHash = "greedy", FirstName = "Jorge", LastName = "Rodriguez", MiddleInitial = "", Address = "6788 Cotter Street", City = "Houston", State = "TX", ZipCode = "77057", Phone = "8178904374", DOB = "32731" }; db.Users.AddOrUpdate(u => U.Email, u31);
            AppUser u32 = new User() { Email = "ra@aoo.com", PasswordHash = "familiar", FirstName = "Allen", LastName = "Rogers", MiddleInitial = "B", Address = "4965 Oak Hill", City = "Austin", State = "TX", ZipCode = "78732", Phone = "5128752943", DOB = "24711" }; db.Users.AddOrUpdate(u => U.Email, u32);
            AppUser u33 = new User() { Email = "st-18452ean@home.com", PasswordHash = "historical", FirstName = "Olivier", LastName = "Saint-Jean", MiddleInitial = "M", Address = "255 Toncray Dr.", City = "San Antonio", State = "TX", ZipCode = "78292", Phone = "2104145678", DOB = "18452" }; db.Users.AddOrUpdate(u => U.Email, u33);
            AppUser u34 = new User() { Email = "ss34@ggmail.com", PasswordHash = "guiltless", FirstName = "Sarah", LastName = "Saunders", MiddleInitial = "J", Address = "332 Avenue C", City = "Austin", State = "TX", ZipCode = "78705", Phone = "5123497810", DOB = "28427" }; db.Users.AddOrUpdate(u => U.Email, u34);
            AppUser u35 = new User() { Email = "willsheff@email.com", PasswordHash = "fre5124510084uent", FirstName = "William", LastName = "Sewell", MiddleInitial = "T", Address = "2365 51st St.", City = "Austin", State = "TX", ZipCode = "78709", Phone = "5124510084", DOB = "15087" }; db.Users.AddOrUpdate(u => U.Email, u35);
            AppUser u36 = new User() { Email = "sheff44@ggmail.com", PasswordHash = "history", FirstName = "Martin", LastName = "Sheffield", MiddleInitial = "J", Address = "3886 Avenue A", City = "Austin", State = "TX", ZipCode = "78705", Phone = "5125479167", DOB = "13829" }; db.Users.AddOrUpdate(u => U.Email, u36);
            AppUser u37 = new User() { Email = "20023ohnsmith187@aool.com", PasswordHash = "s2108321888uirrel", FirstName = "John", LastName = "Smith", MiddleInitial = "A", Address = "23 Hidden Forge Dr.", City = "San Antonio", State = "TX", ZipCode = "78280", Phone = "2108321888", DOB = "20023" }; db.Users.AddOrUpdate(u => U.Email, u37);
            AppUser u38 = new User() { Email = "dustroud@mail.com", PasswordHash = "snakes", FirstName = "Dustin", LastName = "Stroud", MiddleInitial = "P", Address = "1212 Rita Rd", City = "Dallas", State = "TX", ZipCode = "75221", Phone = "2142346667", DOB = "11933" }; db.Users.AddOrUpdate(u => U.Email, u38);
            AppUser u39 = new User() { Email = "ericstuart@aool.com", PasswordHash = "landus", FirstName = "Eric", LastName = "Stuart", MiddleInitial = "D", Address = "5576 Toro Ring", City = "Austin", State = "TX", ZipCode = "78746", Phone = "5128178335", DOB = "11320" }; db.Users.AddOrUpdate(u => U.Email, u39);
            AppUser u40 = new User() { Email = "peterstump@hootmail.com", PasswordHash = "rhythm", FirstName = "Peter", LastName = "Stump", MiddleInitial = "L", Address = "1300 Kellen Circle", City = "Houston", State = "TX", ZipCode = "77018", Phone = "8174560903", DOB = "32733" }; db.Users.AddOrUpdate(u => U.Email, u40);
            AppUser u41 = new User() { Email = "tanner@ggmail.com", PasswordHash = "kindly", FirstName = "Jeremy", LastName = "Tanner", MiddleInitial = "S", Address = "4347 Almstead", City = "Houston", State = "TX", ZipCode = "77044", Phone = "8174590929", DOB = "30092" }; db.Users.AddOrUpdate(u => U.Email, u41);
            AppUser u42 = new User() { Email = "taylord21923ay@aool.com", PasswordHash = "instrument", FirstName = "Allison", LastName = "Taylor", MiddleInitial = "R", Address = "467 Nueces St.", City = "Austin", State = "TX", ZipCode = "78705", Phone = "5124748452", DOB = "21923" }; db.Users.AddOrUpdate(u => U.Email, u42);
            AppUser u43 = new User() { Email = "TayTaylor@aool.com", PasswordHash = "arched", FirstName = "Rachel", LastName = "Taylor", MiddleInitial = "K", Address = "345 Longview Dr.", City = "Austin", State = "TX", ZipCode = "78705", Phone = "5124512631", DOB = "27602" }; db.Users.AddOrUpdate(u => U.Email, u43);
            AppUser u44 = new User() { Email = "teefrank@hootmail.com", PasswordHash = "median", FirstName = "Frank", LastName = "Tee", MiddleInitial = "J", Address = "5590 Lavell Dr", City = "Houston", State = "TX", ZipCode = "77004", Phone = "8178765543", DOB = "24934" }; db.Users.AddOrUpdate(u => U.Email, u44);
            AppUser u45 = new User() { Email = "tuck33@ggmail.com", PasswordHash = "approval", FirstName = "Clent", LastName = "Tucker", MiddleInitial = "J", Address = "312 Main St.", City = "Dallas", State = "TX", ZipCode = "75315", Phone = "2148471154", DOB = "28629" }; db.Users.AddOrUpdate(u => U.Email, u45);
            AppUser u46 = new User() { Email = "avelasco@yaho.com", PasswordHash = "decorate", FirstName = "Allen", LastName = "Velasco", MiddleInitial = "G", Address = "679 W. 4th", City = "Dallas", State = "TX", ZipCode = "75207", Phone = "2143985638", DOB = "23290" }; db.Users.AddOrUpdate(u => U.Email, u46);
            AppUser u47 = new User() { Email = "west34256@pioneer.net", PasswordHash = "grover", FirstName = "Jake", LastName = "West", MiddleInitial = "T", Address = "RR 3287", City = "Dallas", State = "TX", ZipCode = "75323", Phone = "2148475244", DOB = "34256" }; db.Users.AddOrUpdate(u => U.Email, u47);
            AppUser u48 = new User() { Email = "louielouie@aool.com", PasswordHash = "sturdy", FirstName = "Louis", LastName = "Winthorpe", MiddleInitial = "L", Address = "2500 Padre Blvd", City = "Dallas", State = "TX", ZipCode = "75220", Phone = "2145650098", DOB = "19145" }; db.Users.AddOrUpdate(u => U.Email, u48);
            AppUser u49 = new User() { Email = "rwood@voyager.net", PasswordHash = "decorous", FirstName = "Reagan", LastName = "Wood", MiddleInitial = "B", Address = "447 Westlake Dr.", City = "Austin", State = "TX", ZipCode = "78746", Phone = "5124545242", DOB = "33718" }; db.Users.AddOrUpdate(u => U.Email, u49);


            db.SaveChanges();
        }

    }
}